# Generated by Django 2.1.2 on 2018-11-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sync_status',
            field=models.BooleanField(default=False),
        ),
    ]
